### ISSUE TITLE
Make backslash in escapes darker

### ISSUE THREAD

**Issue by pfgithub** [pfgithub/atom-markdown-editor#2]
This is unrelated to the markdown editor, just something I like having in my stylesheet. Add it as a seperate setting doing something like this

```less
.syntax--escape::first-letter{  // initial-letter might work
  display:inline-block;
  opacity:0.1;
}
.syntax--escape:not(.syntax--regexp){ /*:initial-letter might work instead of this gradient*/
  background: -webkit-linear-gradient(right, #5EC4FF 50%, rgba(255,255,255,0.2) 50%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  content: "test\'test";
}
```
